static const char black[]       = "#161320";
static const char gray2[]       = "#575268"; // unfocused window border
static const char gray3[]       = "#6E6C7E";
static const char gray4[]       = "#988BA2";
static const char blue[]        = "#96CDFB";  // focused window border
static const char green[]       = "#ABE9B3";
static const char red[]         = "#F28FAD";
static const char orange[]      = "#F8BD96";
static const char yellow[]      = "#FAE3B0";
static const char pink[]        = "#F5C2E7";
static const char col_borderbar[]  = "#161320"; // inner border
